he = Linux CLI
:hardbreaks:

== Text-fu
=== cut
`cut -c 5 sample.txt` : extrait le 5e caractère de chaque ligne
`cut -f 2 sample.txt` : extrait le 2e champ de chaque ligne avec tab comme délimiteur
-d pour préciser le délimiteur

=== paste
`paste -s sample.txt` : combine toutes les lignes en une séparées par des tabs.
-d pour préciser le délimiteur

=== head / tail
`head` pour les lignes de début, 10 premières par défaut
`tail` pour les lignes de fin, 10 dernières par défaut
-n pour préciser le nombre de lignes à afficher
-f avec tail pour "follow" le fichier en cours de modification (log)

=== expand / unexpand
`expand sample.txt` : transforme les tabs en espaces
unexpand fait l'inverse

=== join / split
`join file1.txt file1.txt` : joint ligne à ligne les 2 fichiers sur la sortie standard
`split file.txt` : crée des fichiers de 1000 lignes par défaut à partir du fichier en entrée nommés x** par défaut

=== sort
`sort file1.txt` : pour trier les lignes dans l'ordre naturel ascendant
-r pour renverser l'ordre, -n par valeur numérique

=== tr
`tr a-z A-Z` : transforme les minuscules tapées dans l'entrée standard en majuscule
-d ello supprime les lettres elo tapées dans l'entrée standard

=== uniq
Renvoie les lignes uniques dans un fichier ou stream
-c pour voir le nombre d'occurrences
-u pour voir les entrées avec une seule occurrence
-d pour voir les entrées dupliquées

=== wc / nl
Pour voir le nombre total de mots dans un fichier
Il affiche respectivement le nombre de lignes, de mots et d'octets
-l, -w, -c respectivement pour isoler ces données
nl affiche les lignes d'un fichier avec leur index en préfixe

. i
. like

=== grep
Pour voir une chaîne qui apparaît dans un fichier ou un stream
-i pour ignorer la casse
Marche également avec des expressions régulières

== Vim / Emacs
/ pour checher un mot (regex), n pour aller vers l'avant, N pour revenir en arrière
h pour gauche, k pour haut, j pour bas, l pour droite
i: insérer du texte après curseur
O: insérer du texte sur la ligne précédente
o: insérer du texte sur la prochaine ligne
a: ajoute du texte après le curseur
A: append text at the end of the line
x: delete selected text
dd: delete current line
y: yank or copy selection
TODO

== User management
System uses UID to manage users, usernames being just friendly way to associate users with their identification
Groups are sets of users identified by a GID
Non human users: root (most powerful), superuser. Non human users may be used to run system daemons or specific programs that has specific permissions.
`sudo`, superuser do, to run command as root. Preferable way because of temporary root access.
`su` to substitute to any user

`/etc/passwd`: contains user information
Columns

. Username
. User's password type. Actual passwords are stored in /etc/shadow. **x** means it is stored in /etc/shadow/, * means that user has no login access
. UID
. GID
. GECOS: comment about user or account ; comma delimited
. Home directory
. User's shell

This file can be modified by hand or with `vipw` but best left to tools like `useradd`, `userdel`
`/etc/passwd`: contains user authentication information
Columns

. Username
. Encrypted password
. Date of last password change
. Min password age: nb of days
. Max password age: nb of days
. Password warning period: nb of days before a password is going to expire
. Password inactivity period: nb of days after a password has expired to allow login with their password
. Account expiration date: date that user will not be able to login
. Reserved field for future use

The system doesn't solely rely on this file but may use other mechanisms such as PAM to replace authentication

`/etc/group`: contains group information
Columns

. Group name
. Group password: no need to set group password because of elevated privilege mechanism like sudo. * in this field
. GID
. List of users

`pwd` to change password, yourself or another user when root

== Permissions
r: read, w: write, x: exec, -: empty
`ls -l` : to see permissions ; in the first column filetype (d for dir) followed by permission grouped by 3 characters, user, group, others
`chmod u+x` add exec permission to user
`chmod ug-w` remove write permission to user and group
`chmod 755` rwx permission to user, and rx permission to group and others. r = 4, w = 2, x = 1.
`chown` to change user or user:group ownership
`chgrp` to change group ownership
`umask 021` take away default set of permissions. Means user has all access (none has been taken away), group has r-x, and exec for others.
**Default umask** on most distros is **022**. To persist umask, startup file, .profile, must be modified.
passwd command is able to modify /etc/shadow because it has the **s** permission. It allows the users who launched the program to get the program file owner's permission as well as execution permission
So when user run password command it runs as root because the latter owns passwd program.
`chmod 4755` to add it (the first 4) or `chmod u+s`
A capital S is the same as s without exec right.
Groups also has an s permission ; `chmod 2755` to add it(the first 2) or `chmod g+s`

The example with passwd does not work by privilege elevation like sudo.
The process has an **effective UID** giving it right accesses.
It also has **real UID** which is the user that launched the process.
It finally has a **saved UID** to switch between real and effective.
The latter is helpful to run with elevated privileges just when it needs to.
When running passwd, effective is root. But you can't change another user password has the program can access your real UID and assess that you cannot do it.
When root access is not needed, it is not used.
Most of the time effective and real are the same.

Last permission is the sticky bit and means that only the owner or root user can delete or modify a file.
Useful for shared directories.
`chmod 1755` to add it(the first 1) or `chmod +t`
When `ls -l` it is the t after the permission

== Processes
`ps` list running processes
Columns

. PID
. TTY: controlling terminal associated with process
. STAT: Status code
. TIME: total CPU usage time
. CMD: Name of executable/command

`ps aux` a displays all processes running, u shows more details about processes, x lists all that don't have any TTY associated
Columns

. USER
. PID
. %CPU: CPU time used divided by the time the process has been running
. %MEM: Ratio of the process's resident set size to the physical memory on the machine
. VSZ: Virtual memory usage of the entire process
. RSS: Resident set size, the non-swapped physical memory that a task has used
. TTY
. STAT
. START: start time
. TIME
. COMMAND

`top` gives real time information about processes. Refreshed by default every 10 seconds

2 types of terminals: **regular terminal devices** and **pseudoterminal devices**
`Ctrl+Alt+F1` to get into TTY1, a regular TTY. Exit with `Ctrl+Alt+F7`
Pseudoterminals are the one with the following format pts/*. Shell is launched under a pts.
Because processes are bound to terminal, shutting it down also closes the associated processes.
Processes run as daemon, launched at the start and terminated when the system is shutdown, have no TTY associated thus there is a **?** in the corresponding column
Process: system allocates memory, CPU, I/O to make a program run. process is an instance of a running program.
The kernel is in charge of processes.
It loads the code in memory, determines and allocates resources and keeps tabs on each process to know at least :

. Status of the process
. Resources the process is using and receives
. The process owner
. Signal handling

At the end of its execution, the used resources are freed up for other processes
When a new process is created, an existing process clones itself using a fork system call that creates a mostly identical child process.
The latter takes a parent PID, PPID, and can use the same program its parent was using before or more often use execve system call to launch up a new program.
The system call destroys the memory management put in place by the kernel and sets up a new one for the new program.
`ps l` to have long format and watch this into action. The PPID of the ps l line is the PID of the line containing the shell.
The first process that permits to launch other is created at boot up time and is called `init` with PID 1.
It runs with root priveleges and runs many processes that keep the system running.

A process can exit using the _exit system call and free up resources for reallocation.
It uses a termination status to inform the kernel it terminates. A status of 0 means the process succeeded.
But the parent process then need to acknowledge the termination by using wait system call and check the child termination status.
Orphan processes (parents die first) are put under the care of init who will eventually call wait system so they can die.
When a child terminates but parent has not called wait yet, kernel turns it into zombie process.
Resources it used are freed but there is still an entry in process table.
Zombies cannot be killed as they are technically dead.
They are "reaped" when parent call wait system otherwise it will be init's responsibility.
Too many zombies take up space on process table and may prevent other processes from running

Signal is a notification to process that something happened.
A signal generated by some event (user who types special keys, hardware/software issues), is delivered and then in a pending state.
The process may then ignore it, catch and perform special routine, terminate, block it depending on its mask.
Common signals:
- SIGHUP or HUP or 1: Hangup, sent when the terminal is closed
- SIGINT or INT or INT: Interrupt == Ctrl+C
- SIGKILL or KILL or 9: Kill, doesn't allow cleanup
- SIGTERM or TERM or 15: Software termination, allows some cleanup first
- SIGSTOP or STOP: Stop, suspend a process

`kill <PID>`: Sends by default TERM but a particular signal can be specified with a -.

Processes use CPU for a small time slice and then pause to allow another to get CPU time.
Normally they should all get an equal amount of CPU time.
However we can influence the CPU by setting niceness/priority.
High number has lower priority. Niceness can be negative.
`nice -n 5 apt upgrade` to launch apt upgrade and set process niceness to 5.
`renice 10 -p 3245` set process with PID 3245 niceness to 10.

STAT values:

. R: running or runnable
. S: interruptible sleep, waiting for an event to complete, such as input from console
. D: uninterruptible sleep, processes that cannot be killed or interrupted with a signal, to make them go away, reboot or fix the issue
. Z : Zombie
. T: Stopped

In Linux, everything is a file, even processes.
Corresponding filesystem is `/proc`.
`cat /proc/<PID>/status` for example.

`sleep <PID> &` ampersand makes it run in the background
`jobs` to see what is executing in the background
`Ctrl-Z` then `bg` to send existing process to the background.
`fg <PID>` to bring it to the foreground.

== Packages
TODO

== Devices
`ls /dev`
`ls -l /dev`
Columns:

. Permissions
. Owner
. Group
. Major Device Number
. Minor Device Number
. Timestamp
. Device name

Device types on the first bit of permissions: c (character), b (block), p (pipe), s (socket)

Character is a device transferring data one character at the time.
Block transfer data in large fixed-sized blocks.
Pipe facilitates communication between 2 or more processes (data are sent to a process instead of a device).
Socket is similar to pipe but can communicate with many processes at once.
The major and minor numbers characterize a device. These numbers are separated by a comma when ls -l on /dev.
The major represents the device driver that is used, the minor tells the kernel which unique device it is in this driver class.

If no mass storage present on your machine, chances are it is using Small Computer System Interface (scuzzy).
It's a protocol used for communication between disks, printers, scanners and other peripherals.
They have a sd prefix: /dev/sda, first hard disk ; /dev/sda3, 3rd partition on first hard disk
Pseudo devices are not physically connected, most are character devices : /dev/null ; /dev/zero (discards input and produces a continuous stream of NULL, zero value, bytes ; /dev/random (random numbers)
Older systems use hd prefix for hard drives instead of sd.

sysfs better manage devices that /dev directory fails to do.
Virtual filesystem mounted on /sys.
Gives more detailed information than in /dev.
/dev allows other programs to access devices, /sys is to view information and manage the device.
`ls /sys/block/sda`

The old way to create device node `mknod /dev/sdb1 b 8 3` with (1) name of the device, (2) its type, (3) its major and minor numbers
To remove a device, we rm it in /dev
`/udev` dynamically creates and removes devices depending on whether they are connected or not.
`udevd` daemon listens to message from the kernel about connected devices.
It parses that information and match it with the rules specified in `/etc/udev/rules.d`.
Depending on that it will most likely create device nodes and symbolic links.
Rules can be added. But systems already have most common defaults.
View the udev DB: `udevadm info --query=all --name=/dev/sda`

`lsusb` to list USB devices
`lspci` to list PCI devices
`lsscsi` to list SCSI devices
Not installed by default

`dd` is useful for converting and copying data. It reads input from a file or data stream and writes it to a file or data stream.
`dd if=/home/pete/backup.img of=/dev/sdb bs=1024`
if is input file, of is output file, bs (in bytes) for block size. bs can use size metrics like k, 1k <==> 1024.
count= argument tells how many we should copy. Not necessary when making a basic copy of data but useful for data transfers.
dd can be used to make backup of anything and restoring it.

== Filesystem
=== Hierarchy
/: root
/bin: essential binaries, most basic commands such as ls or cp
/boot: kernel boot loader files
/dev: device files
/etc: core system configuration files
/home: users' directories
/lib: holds libraries files that binaries can use
/media: used as attachment point for removable media like USB
/mnt: temp mounted filesystems
/opt: optional application software packages
/proc: info about currently running processes
/root: root user home dir
/run: info about the running system since the last boot
/sbin: essential system binaries, usually can only be run by root
/srv: site-specific data served by the system
/tmp: storage for temp files
/usr: user installed software and utilities
/var: used for system logging, user tracking, caches, anything subject to change all the time
=== Types
Many different implementations of filesystem. VFS (virtual file system) provides an abstraction layer.
Thus programs can access them without having to know the implementation.
A single disk may have several FS depending on its partition.

Journaling is available in most filesystems.
Actions to be completed are written in a log file (journal) so that if there is any interruption (power loss), the system can recover from it.
Once finished, the task is marked as done in the journal.
Filesystems without journal are subject to file corruption and inconstant state when booting back up. They have to check to make sure everything is OK.
This step may take time.
Filesystems with don't need this step and boot quicker because just have to look at the journal.
The system know where you left off even if task is incomplete.

ext4: most current version of native linux filesystem. Compatible with older versions ext2 and 3 and supports disk volumes up to 1 exabyte and file size up to 16 TB.
btrfs: "Better or Butter FS" new linux FS that comes with snapshots, incremental backups, performance increase and much more. Not quite stable and compatible yet.
xfs: high performance journaling FS, great for a system with large files such as media server
NTFS and FAT: windows FS
HFS+: Macintosh FS
`df -T`: display information about disk, including partition FS

=== Disk anatomy
Partitions are reprensented as block devices (/dev/sda1).
Every disk has a partition table containing information about where partitions begin, end, if it is bootable, disk sectors it owns, etc.
2 main partition schemes are used: Master Boot Record (MBR), GUID Partition Table (GPT)
Partitions cannot overlap. Disk not affected to a partition is free space.
Partition can have a specific filesystem or be dedicated to swap.

MBR
- Traditional, was used as a standard
- Can have primary, extended and logical partitions
- limit of 4 primary partitions
- primary may be turned to extended to make additional partitions. Inside extended, logical partitions can be added
- supports disks up to 2 TB

GPT
- becoming the new standard
- one type of partition
- each partition has a GUID (globally unique ID)
- used in conjunction with UEFI based booting

Filesystem structure
- boot block: located in the first few sectors, contains information used to boot the OS rather than the filesystem
- super block: single block after the boot block; contains info about the filesystem, such as the size fo the inode table, size of logical blocks and of the filesystem
- Inode table: like a DB managing our files. Each file or dir has a unique entry and it has various information about the file
- Data blocks: actual data for the files and dir

`sudo parted -l`  to display information about disk and partition table

=== Disk partitioning
`fdsik` supports MBR but not GPT
`parted` supports both MBR and GPT. Its GUI version is `gparted`
`gdisk` supports GPT but not MBR
`mkpart primary 123 4567` to create, with first number being the start point and the other the end point.
Each partition has these information.
`resize 2 123 4567` to resize, partition number, start point and end point.
After the partition, we can create a FS: `sudo mkfs -t ext4 /dev/sdb2`

=== Mount/umount
Used to mount/unmount device to a dir
`sudo mount -t ext4 /dev/sdb2 /mydrive`
If the device name changes (kernel names them in the order it finds them), we can use UUID instead of a name:
`sudo blkid`
Then the mount command is `sudo mount UUID=$UUID /mydrive`
To mount automatically FS at startup, we can add them to a file called `/etc/fstab`
A line contains following info:

- UUID
- Mount point: dir the FS is mounted to
- FS type
- Options
- Dump: used by the dump utility to decide when to make a backup, should be set to 0
- Pass: used by fsck to decide what order FSs should be checked, if 0, not checked

=== Swap
Used to allocate virtual memory to our system. The system uses this partition to swap pieces of memory of idle processes to avoid being bogged on memory
To create it nothing should be on the partition.
`mkswap /dev/sdb2` to initialize
`swapon /dev/sdb2` to enable
To make it persist on bootup, add an entry to `/etc/fstab`
To remove it, `swapoff /dev/sdb2`
General advice is to allocate twice the RAM

=== Disk usage
`df -h` shows the utilization of the currently mounted FS
`du -h $dir` to show the disk usage of $dir

=== Repair FS
Through `fsck`
Usually run when booting up
When launching manually (because FS is f* up), be sure to be on an unmounted disk
`sudo fsck /dev/sda`

=== inodes
inode table is the table that manages the files in a FS
inode is an entry in this table and there is one for each file
This entry describes everything about the file:

- File type: regular file, dir, char device, etc.
- Owner
- Group
- Access permissions
- Timestamps: mtime (last modification), ctime (last attribute change), atime (last access)
- nb of hardlinks to the file
- size of tjhe file
- nb of blocks allocated to the file
- pointers to the data blocks of the file (most important)

The space for inodes is allocated when the FS is created
There are algorithms to compute how much inode space is needed depending on the volume of the disk.
You can run out of space for inodes and thus being unable to create new files (storage depends on data and data DB), but that occurs rarely.
`df -i` to see how many inodes are left on your system
inodes are identified by number ; it is sequentially assigned when the file is created
this link may be deleted because file does not exist anymore ; it is then reused for another file
`ls -li` to view the inode associated to file (1st field)
inodes point to the actual data location on disk, because it is probably not stored sequentially.
In a typical FS, each inode contains 15 pointers.
The first 12 point directly to the data blocks.
The 14th points to another nested block of pointers.
The 15th also points to another nested block of pointers
Small could use the first 12 pointers when larger files can be found with the nest of pointers, but the structure is still the same

=== Links
Symbolic links, symlinks, are files that link to another file by its filename
when a symlink is modified, the underlying file gets also modified
symlinks do not reference by inode so can be used across FS as it uses the filename. inodes are FS dependent.
Hardlinks create a file with a link to the same inode.
Hardlinks stay accessible even if the underlying file is deleted.
`ls -li` third column is the link count (hardlinks)
when a file is deleted this is decremented and the inode is deleted once the count equals 0
`ln file_name` for hardlink
`ln -s file_name` for symlink

== Boot the system
4 stages:

- BIOS: Basic Input/Output System initializes the hardware and make sure with a Power-On Self Test (POST) asserting the hardware is good to go. Its main job is to load up the bootloader.
- Bootloader: loads the kernel into memory and then starts the kernel with a set of kernel parameters. GRUB is one of the most common and a universal linux standard
- Kernel: as soon as it is started, it initializes devices and memory and load up the init process
- Init process: first process that gets started, starts and stops essential service process on the system. 3 major implementations on Linux distributions

=== BIOS
It performs system integrity checks. a firmware that comes most common in IBM PC compatible computers
Once the BIOS boots up the hard drive, it searches for the boot block to figure out how to boot up the system.
Depending on partition type, it'll look to MBR or GPT
MBR is located in the first 512 bytes. it contains the code to load another program that actually loads up the bootloader
UEFI, unified extensible firmware interface, was designed to be successor to BIOS, and most hardware comes with UEFI installed
GPT was intended for use with EFI but is not necessary for booting on a GPT disk
The first sector of GPT is reserved for a protective MBR to make it possible to boot a BIOS-based machine
UEFI stores all the information about startup in an .efi file stored on a special partition called EFI system partition on the hardware
This partition contains the bootloader

=== Bootloader
Its responsabilities:

- booting into an OS, even non-linux OS
- select a kernel to use
- specify kernel parameters

the most common bootloader for linux is GRUB. The others: LILO, efilinux, SYSLINUX
the kernel parameters for GRUB can be found at startup by pressing the *e* key
the parameters:

- inintrd: location of initial RAM disk
- BOOT_IMAGE: location of the root filesystem, the kernel searches inside to find init. represented by its UUID or device name
- ro: mounts the filesystem as read-only
- quiet: to avoid displaying message going on in the background during the boot
- splash: lets the splash screen be shown

=== Kernel
During bootup, the kernel depends on a temporary root FS containing just the essential modules the kernel needs to get to the rest of the hardware
In older Linux this was initrd's job (initial ram disk)
The kernel would mount the initrd, get the necessary bootup drivers, then when it was done loading everything it needed, it would replace teh initrd with the actual root FS
These days, the kernel uses the initramfs, a temporary root FS built into the kernel itself to load all the drivers for the real root FS and doesn't have to locate initrd
When all the modules are loaded, the kernel creates a root device and mount the root partition.
It is mounted in RO mode first so that fsck can run safely and check the system integrity.
Then it remounts in RW mode and the kernel locates the init program and executes it.

=== Init
First process to get started and starts all the other essential services on the system
3 major implementations of init on Linux:
- System V inint (sysv): traditional init system. sequentially starts and stops processes based on startup scripts. The state of the machine is denoted by runlevels, each one starts and stops the machine in a different way
- upstart: the init found on older Ubuntu installations. it uses the idea of jobs and events and works by starting jobs that performs certain actions in response to events
- systemd: the new standard for init and goal oriented. Basically you have a goal you want to achieve and systemd tries to satisfies the goal's dependencies to complete it

== Kernel
The core of the OS.
The linux OS can be organized in 3 levels of abstraction.
The most basic one is hardware including the CPU, memory, HDs, networking ports, etc.
The next one is the kernel handling processes, memory management, device communication, system calls, set up our FS, etc.
This level talk to the hardware to make sure it does what the processes have to do.
The final one is the user space including the shell, the programs we run, the graphics, etc.

=== Privilege levels
In kernel mode, contrary to user mode, access to hardware is complete.
In user mode, a small amount of memory and CPU is accessible.
Doing anything involving reading/writing to disks, controlling the network is done using the kernel mode
Separating the modes is effective in many cases like for an infected machine that won't have access to the low level.
These levels of rights are called privilege levels and often described as protection rings.
2 main levels/modes in x86 architecture.
Ring #3 is the privilege that user mode applications run in.
#0 is the privilege the kernel runs in. This ring is given full trust.

=== System calls
syscall provide the user space a way to request the kernel to do something for us.
Certain services are available through the syscall API
These services allow us to read or write to a file, modify memory usage, modify our network, etc.
Their amount are fixed and the system already has a table of what system calls exist and each one has a unique ID
A program like ls contains a system call wrapper. Inside it, it invokes that executes a trap.
The trap is then caught by the system call handler and references the system call in the syscall table.
ls is executed in non-privileged mode first.
It then switches the mode to do a lot of things like looking up the syscall number/
Finally it executes the function you wanted to run.
`strace ls` to debug the execution of ls and see how it is executed

=== Kernel
`uname -r` prints all of the kernel release version
The kernel may be install or updated separately from the distro
When a new kernel is installed it usually adds files to /boot
*vmlinuz* is the actual kernel
*initrd* is the temporary filesystem before loading the kernel
*system.map* symbolic lookup table
*config* kernel configuration settings, can be used to set which modules are loaded
Old versions of these files may be deleted if /boot runs out of space
`lsmod` to see the loaded modules and their dependencies
`sudo modprobe bluetooth` to load bluetooth modules
use -r to remove a module
To load on bootup, modifiy `/etc/modprobe.d` dir and add a configuration file
To avoid loading on bootup, `blacklist module_name` in the configuration file

== Init
Main purpose of init is to start & stop essential processes on the system
3 major implementations of init: System V, upstart, systemd

=== SystemV
This is what you use if you have a `/etc/inittab` file
It starts and stops processes sequentially
sys v deals with dependencies through scripts which starts and stops services
Used because it is relatively easy to solve dependencies
Performance is not great because one thing, start or stop, at a time
sys v defines 0 to 6 runlevels for the machine
0: shutdown
1: single user mode
2: multiuser mode without networking
3: multiuser mode with networking
4: unused
5: multiuser mode with networking and GUI
6: reboot

At each runlevel, it looks into the corresponding configuration directory to
execute contained scripts
They are located in `/etc/rc.d/rc[runlevel].d` or `/etc/init.d`
scripts that start with s (start) or k (kill) will run on startup and shutdown
The default runlevel the machine boots into is inside `/etc/inittab`
It is slowly being replaced and runlevels are used in other init implementations to support services
that are only started or stopped using sys v init scripts
`service --status-all` list services
`sudo service networking [start/stop/restart]`
 Those commands can be used to Upstart services as well

 === Upstart
Developed by Canonical, the init implmentation on ubuntu for a while, however systemd is used on modern ubuntu
Created to improve upon the issues with sys v such as strict startup processes, blocking of tasks, etc.

=== systemd
How it works:
- systemd loads its config files, usually located in /etc/systemd/system, usr/lib/systemd/system
- Determines its boot goal, usually default.target
- Figures out the dependencies of the boot target and activate them

systemd boots into different targets:
- poweroff.target: shutdown
- rescue.target: single user modern
- multi-user.target: multiuser with networking
- graphical.target: multiuser with networking and GUI
- reboot.target

It works with units.
It does not just stop and start services.
It can mount FS, monitor network sockets, etc.
It has then different types of units:
- Service units: services started and stopped, these unit files end in .service
- Mount units: mount FS, ends in .mount
- Target units: group other units, ends in .target
Once a unit is activated, every unit below are activated

Unit file example
```
[Unit]
Description=My Foobar
Before=bar.target

[Service]
ExecStart=/usr/bin/foobar

[Install]
WantedBy=multi-user.target
```

`systemctl list-units` list units
`systemctl status networking.service` status of unit
`sudo systemctl [start/stop/restart/enable/disable] networking.service`

=== Power states
`sudo shutdown -h now`
`sudo shutdown -h +2`
`sudo shutdown -r now` or `sudo reboot` restart


Source : https://linuxjourney.com/
