= Linux CLI
:hardbreaks:

== Text-fu
=== cut
`cut -c 5 sample.txt` : extrait le 5e caractère de chaque ligne
`cut -f 2 sample.txt` : extrait le 2e champ de chaque ligne avec tab comme délimiteur
-d pour préciser le délimiteur

=== paste
`paste -s sample.txt` : combine toutes les lignes en une séparées par des tabs.
-d pour préciser le délimiteur

=== head / tail
`head` pour les lignes de début, 10 premières par défaut
`tail` pour les lignes de fin, 10 dernières par défaut
-n pour préciser le nombre de lignes à afficher
-f avec tail pour "follow" le fichier en cours de modification (log)

=== expand / unexpand
`expand sample.txt` : transforme les tabs en espaces
unexpand fait l'inverse

=== join / split
`join file1.txt file1.txt` : joint ligne à ligne les 2 fichiers sur la sortie standard
`split file.txt` : crée des fichiers de 1000 lignes par défaut à partir du fichier en entrée nommés x** par défaut

=== sort
`sort file1.txt` : pour trier les lignes dans l'ordre naturel ascendant
-r pour renverser l'ordre, -n par valeur numérique

=== tr
`tr a-z A-Z` : transforme les minuscules tapées dans l'entrée standard en majuscule
-d ello supprime les lettres elo tapées dans l'entrée standard

=== uniq
Renvoie les lignes uniques dans un fichier ou stream
-c pour voir le nombre d'occurrences
-u pour voir les entrées avec une seule occurrence
-d pour voir les entrées dupliquées

=== wc / nl
Pour voir le nombre total de mots dans un fichier
Il affiche respectivement le nombre de lignes, de mots et d'octets
-l, -w, -c respectivement pour isoler ces données
nl affiche les lignes d'un fichier avec leur index en préfixe
1. i
2. like

=== grep
Pour voir une chaîne qui apparaît dans un fichier ou un stream
-i pour ignorer la casse
Marche également avec des expressions régulières

== Vim / Emacs
/ pour checher un mot (regex), n pour aller vers l'avant, N pour revenir en arrière
h pour gauche, k pour haut, j pour bas, l pour droite
i: insérer du texte après curseur
O: insérer du texte sur la ligne précédente
o: insérer du texte sur la prochaine ligne
a: ajoute du texte après le curseur
A: append text at the end of the line
x: delete selected text
dd: delete current line
y: yank or copy selection

== User management
System uses UID to manage users, usernames being just friendly way to associate users with their identification
Groups are sets of users identified by a GID
Non human users: root (most powerful), superuser. Non human users may be used to run system daemons or specific programs that has specific permissions.
`sudo`, superuser do, to run command as root. Preferable way because of temporary root access.
`su` to substitute to any user

`/etc/passwd`: contains user information
Column meaning:
1. Username
2. User's password type. Actual passwords are stored in /etc/shadow. **x** means it is stored in /etc/shadow/, * means that user has no login access
3. UID
4. GID
5. GECOS: comment about user or account ; comma delimited
6. Home directory
7. User's shell
This file can be modified by hand or with `vipw` but best left to tools like `useradd`, `userdel`
`/etc/passwd`: contains user authentication information
Column meaning:
1. Username
2. Encrypted password
3. Date of last password change
4. Min password age: nb of days
5. Max password age: nb of days
6. Password warning period: nb of days before a password is going to expire
7. Password inactivity period: nb of days after a password has expired to allow login with their password
8. Account expiration date: date that user will not be able to login
9. Reserved field for future use
The system doesn't solely rely on this file but may use other mechanisms such as PAM to replace authentication

`/etc/group`: contains group information
Column meaning:
1. Group name
2. Group password: no need to set group password because of elevated privilege mechanism like sudo. * in this field
3. GID
4. List of users

`pwd` to change password, yourself or another user when root

== Permissions
r: read, w: write, x: exec, -: empty
`ls -l` : to see permissions ; in the first column filetype (d for dir) followed by permission grouped by 3 characters, user, group, others
`chmod u+x` add exec permission to user
`chmod ug-w` remove write permission to user and group
`chmod 755` rwx permission to user, and rx permission to group and others. r = 4, w = 2, x = 1.
`chown` to change user or user:group ownership
`chgrp` to change group ownership
`umask 021` take away default set of permissions. Means user has all access (none has been taken away), group has r-x, and exec for others.
**Default umask** on most distros is **022**. To persist umask, startup file, .profile, must be modified.
passwd command is able to modify /etc/shadow because it has the **s** permission. It allows the users who launched the program to get the program file owner's permission as well as execution permission
So when user run password command it runs as root because the latter owns passwd program.
`chmod 4755` to add it (the first 4) or `chmod u+s`
A capital S is the same as s without exec right.
Groups also has an s permission ; `chmod 2755` to add it(the first 2) or `chmod g+s`

The example with passwd does not work by privilege elevation like sudo.
The process has an **effective UID** giving it right accesses.
It also has **real UID** which is the user that launched the process.
It finally has a **saved UID** to switch between real and effective.
The latter is helpful to run with elevated privileges just when it needs to.
When running passwd, effective is root. But you can't change another user password has the program can access your real UID and assess that you cannot do it.
When root access is not needed, it is not used.
Most of the time effective and real are the same.

Last permission is the sticky bit and means that only the owner or root user can delete or modify a file.
Useful for shared directories.
`chmod 1755` to add it(the first 1) or `chmod +t`
When `ls -l` it is the t after the permission

Source : https://linuxjourney.com/